version: 3

tasks:
  default:
    deps:
      - gocli
      - gox
    desc: Build the project using Go build command

  build:single:
    cmds:
      - MOD_SUM=$(sha256sum go.sum | cut -d" " -f1 | cut -c1-16) goreleaser build --snapshot --clean --single-target
    desc: Build the project using GoReleaser

  build:all:
    cmds:
      - MOD_SUM=$(sha256sum go.sum | cut -d" " -f1 | cut -c1-16) goreleaser build --snapshot --clean
    desc: Build the project using GoReleaser in test mode

  release:
    cmds:
      - MOD_SUM=$(sha256sum go.sum | cut -d" " -f1 | cut -c1-16) goreleaser release --clean
    desc: Create a new release using GoReleaser

  test:
    cmds:
      - go test ./...
    desc: Run tests

  gocli:
    cmds:
      - go build ./cmd/gocli
    desc: Build the project using the default Go build command (Without Version Info)

  gox:
    cmds:
      - go build ./cmd/gox
    desc: Build the gox tool
